//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wafa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Case()
        {
            this.sessions = new HashSet<session>();
        }
    
        public int case_id { get; set; }
        public Nullable<int> case_no { get; set; }
        public Nullable<System.DateTime> issuance_date { get; set; }
        public Nullable<int> court_id { get; set; }
        public Nullable<int> admin_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> lawyer_id { get; set; }
        public string documents { get; set; }



        public virtual Admin Admin { get; set; }
        public virtual Client Client { get; set; }
        public virtual Court Court { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<session> sessions { get; set; }
        public virtual Lawyer Lawyer { get; set; }

    }
}
