//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wafa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseViewModel
    {
        public int CaseId { get; set; }
        public Nullable<int> CaseNumber { get; set; }
        public Nullable<System.DateTime> CaseDate { get; set; }
        public string CourtName { get; set; }
        public Nullable<int> LawyerId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
    }
}
