//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wafa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class session
    {
        public int session_id { get; set; }
        public Nullable<System.DateTime> session_data { get; set; }
        public Nullable<int> session_number { get; set; }
        public Nullable<int> case_id { get; set; }
        public Nullable<int> court_id { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual Court Court { get; set; }
    }
}
